# Generated by Django 4.1.4 on 2022-12-17 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.TextField(help_text='Ordered/Canceled', verbose_name='Status of order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='OrdersFromBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(blank=True, verbose_name="User's name")),
                ('chat_id_user', models.PositiveIntegerField(verbose_name='User ID')),
                ('services_name', models.TextField(blank=True, help_text="don't touch", verbose_name='Service Name')),
                ('order_price', models.IntegerField(blank=True)),
                ('is_active', models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manager.statusorder', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
