# Generated by Django 4.1.4 on 2022-12-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersfrombot',
            name='user_contact_info',
            field=models.TextField(blank=True, help_text="don't touch", verbose_name='User INFO'),
        ),
    ]
