# Generated by Django 4.1.4 on 2022-12-17 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementsCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement_name', models.TextField(help_text='...', verbose_name='Ad name')),
                ('advertisement_income', models.IntegerField(help_text='how much?', verbose_name='Income')),
                ('advertisement_expenditure', models.IntegerField(help_text='how much?', verbose_name='Expenditure')),
                ('advertisement_profit', models.IntegerField(blank=True, help_text='how much? in %', verbose_name='Profit')),
            ],
            options={
                'verbose_name': 'Advertisement Calculator',
            },
        ),
        migrations.CreateModel(
            name='AsksForFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_name', models.TextField(help_text='Write Some Question', max_length=48, verbose_name='FAQ')),
                ('faq_ask', models.TextField(help_text='...', verbose_name='ASK')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='ClientsReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(verbose_name='Review Text')),
                ('review_user', models.TextField(help_text='Who?', null=True, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Client Review',
            },
        ),
        migrations.CreateModel(
            name='CompanyPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_post', models.TextField(help_text='Courier/CEO/Head', verbose_name='Post in company')),
            ],
            options={
                'verbose_name': 'POST IN COMPANY',
            },
        ),
        migrations.CreateModel(
            name='ServicesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.TextField(help_text='...', verbose_name='Service')),
                ('service_price', models.IntegerField(help_text='how much?', verbose_name='Price')),
                ('service_description', models.TextField(help_text='Trala-la', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Service Calculator',
            },
        ),
        migrations.CreateModel(
            name='StaffinCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.TextField(help_text='Alex Wednesday jr.', verbose_name='Person name')),
                ('telegram_userid', models.IntegerField(default=None, verbose_name='ID')),
                ('telegram_nickname', models.TextField(default=None, help_text='Skinny Jeans', verbose_name='Telegram Nickname')),
                ('telegram_username', models.TextField(default=None, help_text='@SomeBody', verbose_name='Telegram Username')),
                ('person_payment', models.IntegerField(help_text='how much?', verbose_name='Person payment')),
                ('person_post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='commands.companyposts', verbose_name='Post in company')),
            ],
            options={
                'verbose_name': 'Staffs',
            },
        ),
    ]
