# Generated by Django 4.1.4 on 2022-12-17 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceslist',
            options={'verbose_name': 'Service'},
        ),
    ]
