# Generated by Django 4.1.4 on 2022-12-30 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0002_alter_serviceslist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisementscalculator',
            options={'verbose_name': 'Калькулятор рекламы'},
        ),
        migrations.AlterModelOptions(
            name='asksforfaq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.AlterModelOptions(
            name='clientsreviews',
            options={'verbose_name': 'Отзыв пользователя', 'verbose_name_plural': 'Отзыв пользователя'},
        ),
        migrations.AlterModelOptions(
            name='companyposts',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='serviceslist',
            options={'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервисы'},
        ),
        migrations.AlterModelOptions(
            name='staffincompany',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='advertisementscalculator',
            name='advertisement_expenditure',
            field=models.IntegerField(help_text='Сколько', verbose_name='Потери'),
        ),
        migrations.AlterField(
            model_name='advertisementscalculator',
            name='advertisement_income',
            field=models.IntegerField(help_text='Сколько', verbose_name='Вложения'),
        ),
        migrations.AlterField(
            model_name='advertisementscalculator',
            name='advertisement_name',
            field=models.TextField(help_text='Гугл Адс', verbose_name='Название рекламы'),
        ),
        migrations.AlterField(
            model_name='advertisementscalculator',
            name='advertisement_profit',
            field=models.IntegerField(blank=True, help_text='Результат в %, оставьте это поле пустым', verbose_name='Доход'),
        ),
        migrations.AlterField(
            model_name='asksforfaq',
            name='faq_ask',
            field=models.TextField(help_text='Ответ', verbose_name='ASK'),
        ),
        migrations.AlterField(
            model_name='asksforfaq',
            name='faq_name',
            field=models.TextField(help_text='Какой-то вопрос', max_length=48, verbose_name='FAQ'),
        ),
        migrations.AlterField(
            model_name='clientsreviews',
            name='review_text',
            field=models.TextField(verbose_name='Отзывы'),
        ),
        migrations.AlterField(
            model_name='clientsreviews',
            name='review_user',
            field=models.TextField(null=True, verbose_name='Пользователь который оставил'),
        ),
        migrations.AlterField(
            model_name='companyposts',
            name='person_post',
            field=models.TextField(help_text='Курьер/CEO/Глава', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='serviceslist',
            name='service_description',
            field=models.TextField(help_text='Опишите услугу', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='serviceslist',
            name='service_name',
            field=models.TextField(help_text='Имя услуги', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='serviceslist',
            name='service_price',
            field=models.IntegerField(help_text='Цена за единицу', verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='staffincompany',
            name='person_name',
            field=models.TextField(help_text='Alex Wednesday jr.', verbose_name='Имя человека'),
        ),
        migrations.AlterField(
            model_name='staffincompany',
            name='person_payment',
            field=models.IntegerField(verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='staffincompany',
            name='person_post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='commands.companyposts', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='staffincompany',
            name='telegram_nickname',
            field=models.TextField(default=None, help_text='Skinny Jeans', verbose_name='Telegram никнейм'),
        ),
        migrations.AlterField(
            model_name='staffincompany',
            name='telegram_userid',
            field=models.IntegerField(default=None, verbose_name='ID телеграмма'),
        ),
        migrations.AlterField(
            model_name='staffincompany',
            name='telegram_username',
            field=models.TextField(default=None, help_text='@SomeBody', verbose_name='Telegram имя'),
        ),
    ]
