# Generated by Django 4.1.4 on 2022-12-30 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0005_alter_clientsreviews_review_chat_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyposts',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.DeleteModel(
            name='StaffinCompany',
        ),
    ]
