# Generated by Django 4.1.4 on 2022-12-30 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0007_delete_companyposts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisementscalculator',
            options={'verbose_name': 'Калькулятор рекламы', 'verbose_name_plural': 'Калькулятор рекламы'},
        ),
    ]
